[env:s3-st7735-hybrid]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.speed = 921600

build_flags =
    ${env.build_flags}
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D _DISABLE_MASS_STORAGE=1

    -D DDEVICE_NAME="\"S3-ST7735-Hybrid\""
    -D DISABLE_OTA=1

    ; --- CONFIGURAÇÃO DA TELA ST7735 (1.8" - 128x160) ---
    -D TFT_DATABUS_N=0
    -D TFT_DISPLAY_DRIVER_N=0
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160
    -D ST7735_GREENTAB3=1
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_CS=16
    -D TFT_DC=7
    -D TFT_RST=15
    -D TFT_MOSI=6
    -D TFT_SCLK=5
    -D TFT_MISO=41
    -D TFT_BL=4
    -D TFT_BACKLIGHT_ON=HIGH

    ; --- TOUCH RESISTIVO (XPT2046) ---
    -D HAS_RESISTIVE_TOUCH=1
    -D CYD28_TouchR_CS=14
    -D CYD28_TouchR_IRQ=2
    -D CYD28_TouchR_MISO=41
    -D CYD28_TouchR_MOSI=6
    -D CYD28_TouchR_CLK=5
    -D SPI_TOUCH_FREQUENCY=2500000

    ; --- CARTÃO SD ---
    -D SDCARD_CS=40
    -D SDCARD_SCK=5
    -D SDCARD_MISO=41
    -D SDCARD_MOSI=6

    ; --- JOYSTICK E BOTÕES FÍSICOS (Redundância de Navegação) ---
    -D DHAS_BTN=1
    -D DBTN_ALIAS="\"Mid\""
    -D DBTN_PIN=0
    -D DBTN_ACT=LOW
    -D DJOY_X=12
    -D DJOY_Y=13
    -D DSEL_BTN=14
    -D DHAS_SCREEN=1
    -D DHAS_TOUCH=1
    -D DROTATION=1
	
